export const constants = {
    nextBallElement     : document.getElementById('next-weight'),
    leftWeightElement   : document.getElementById('left-weight'),
    rightWeightElement  : document.getElementById('right-weight'),
    colorElement        : document.getElementById('color'),
    screenElement       : document.getElementById('screen'),
    seesawElement       : document.getElementById('seesaw'),
    tiltAngleElement    : document.getElementById('tilt-angle'),
    logs                : document.getElementById('logs'),
    refreshBTN          : document.getElementById('refreshBTN'),
    gameBoxElement      : document.getElementById('game-box'),
    ball                : document.getElementById('ball'),
    colors              : ['#3599db', '#34495e', '#1abc9c', '#2ecc71', '#e67e22', '#e74c3c', '#9b59b6'],
    maxKG               : 10,
    tiltMultiplier      : 30,
    maxTiltAngle        : 30,
    minTiltAngle        : -30,
    toRadians           : Math.PI / 180,
}